In [73]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report


# Reading dataset

In [86]:
dataset=np.genfromtxt("C:\\Users\Dharmik\Desktop\data.csv",delimiter=",")

x=dataset[1:,1:-1] #shape(1000,28)

y_raw=dataset[1:,-1]

y=y_raw.reshape((1000,1)) #shape(1000,1)

y=y.astype('int')

x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.25, random_state=42)

len_y=len(y_train)



In [87]:
print(x_train.shape)
print(y_train.shape)

(750, 28)
(750, 1)


In [88]:
epochs=1000
learning_rate=0.01
hiddenlayer_num=20
n=x.shape[0]


# Sigmoid and its derivative


In [89]:
def sigmoid(z):
    return (1/(1+np.exp(-z)))

def sigmoidDerivative(sigmoid):
    return sigmoid * (1 - sigmoid)


# Initializing weights


In [90]:
W1=np.random.rand(hiddenlayer_num,x_train.shape[1])*0.01 #shape(20,28)
W2=np.random.rand(10,hiddenlayer_num)*0.01 #shape(10,20) 10 is the number of classes
print(W1.shape) 
print(W2.shape)

(20, 28)
(10, 20)


# Feedforward

In [91]:
def feedforward(x_train,W1,W2):
    A1 = sigmoid(np.dot(W1,x_train.T))     #shape(20,1000)
    A2 = sigmoid(np.dot(W2,A1)).T          #shape(1000,10)
    print(A1.shape)
    print(A2.shape)
    return A2,A1

A2,A1 = feedforward(x_train,W1,W2) #defining variables for the output of feedforward network which will be used in backpropagation


(20, 750)
(750, 10)


# One hot Encoder

In [92]:
def onehotencoder(onehot_raw):
    onehot_raw=np.zeros((x_train.shape[0],10))# to create a matrix of zeros which will provide a frameworkto create one hot encoded matrix of y
    for i in range(len_y):
        onehot_raw[i][int(y[i])]=1  
    return onehot_raw   #creates a onehotencoded matrix of (1000,10) shape

print(onehotencoder(y_train), onehotencoder(y_train).shape,sep='\n \n')
#at first the onehotencoded matrix was not coming out to be proper. that is because the y matrix had dtype of float and not int. so when I type converted it into int dtpye the proper one hot encoded matrix was obtained.


[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]
 
(750, 10)


# Backpropagation

In [93]:
Y=onehotencoder(y_train) #onehotencoded y matrix

def backpropagation(W2,W1,A2,A1,x,Y):
    for iters in range(epochs):
        Z1 = np.dot(x_train, W1.T)      #shape(1000,20)
        A1 = sigmoid(Z1)          #shape(1000,20)
        Z2 = np.dot(A1, W2.T)     #shape(1000,10)
        A2 = sigmoid(Z2)          #shape(1000,10)
        cost = np.sum((Y * np.log(A2)) + ((1-Y) * np.log(1-A2))) * (-1/n)
        
        #calculating derivatives of Z2,W2,A1,W1 wrt cost function
        
        dZ2=(-1/n)*(Y-A2)                #shape(1000,10)
        dW2=np.dot(dZ2.T, A1)            #shape(10,20)
        dA1=np.dot(dZ2,W2)               #shape(1000,20)
        dZ1=   dA1*sigmoidDerivative(A1) #shape(1000, 20)    ####################
        dW1=np.dot(x_train.T,dZ1).T      #shape(28,10)
        
        #updating weights 
        
        W2=W2-learning_rate*dW2
        W1=W1-learning_rate*dW1
        
    
    return W2,W1
W2,W1=backpropagation(W2,W1,A2,A1,x,Y)

print(W2.shape)
print(W1.shape)

(10, 20)
(20, 28)


# Test Function

In [104]:
def test(x,y,W1,W2):
    Z1 = np.dot(W1, x_test.T) 
    A1 = sigmoid(Z1) 
    Z2 = np.dot(W2, A1)
    A2 = sigmoid(Z2)
    
    
test(x_test,y_test,W1,W2)
    

(250, 1) [13]
