In [1]:
import numpy as np

# Reading dataset

In [3]:
dataset=np.genfromtxt("data.csv",delimiter=",")

x=dataset[1:,1:-1] #shape(1000,28)

y_raw=dataset[1:,-1]

y=y_raw.reshape((1000,1)) #shape(1000,1)

len_y=len(y)

In [5]:
print(y.shape)
print(x.shape)

(1000, 1)
(1000, 28)


In [8]:
epochs=1000
learning_rate=0.01
hiddenlayer_num=20
n=x.shape[0]


# Sigmoid and its derivative


In [9]:
def sigmoid(z):
    return (1/(1+np.exp(-z)))

def sigmoidDerivative(sigmoid):
    return sigmoid * (1 - sigmoid)

# Initializing weights


In [11]:
W1=np.random.rand(hiddenlayer_num,x.shape[1])*0.001 #shape(20,28)
W2=np.random.rand(10,hiddenlayer_num)*0.01 #shape(10,20) 10 is the number of classes

print(W1.shape)
print(W2.shape)


(20, 28)
(10, 20)


# Feedforward

In [16]:
def feedforward(x,W1,W2):
    A1 = sigmoid(np.dot(W1,x.T))     #shape(20,28) #wrongg!! 28 --> 1000 (20, 1000)
    A2 = sigmoid(np.dot(W2,A1)).T    #shape(10,28) --> (1000, 10) obv man... you need an output for each training example
    print(A1.shape)
    print(A2.shape)
    
    return A2,A1

A2,A1 = feedforward(x,W1,W2) #defining variables for the output of feedforward network which will be used in backpropagation


(20, 1000)
(1000, 10)


# One hot Encoder

In [23]:
def onehotencoder(y):
    onehot_raw=np.zeros((1000,10))# to create a matrix of zeros which will provide a frameworkto create one hot encoded matrix of y
    for i in range(len_y):
#         print(y[i])
        onehot_raw[i][int(y[i]-1)]=1  
    return onehot_raw   #creates a onehotencoded matrix of (1000,10) shape

y_onehot = onehotencoder(y)

In [24]:
print(y_onehot)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


# Backpropagation

In [32]:
Y=onehotencoder(y) #onehotencoded y matrix

def backpropagation(W2,W1,A2,A1,Y):
    cost=Y-A2 #shape(1000,10)
    for iters in range(epochs):
        Z1 = np.dot(W1, x.T) 
        A1 = sigmoid(Z1) 
        Z2 = np.dot(w2, A1).T
        A2 = sigmoid(Z2) 
        cost = np.sum((Y * np.log(A2)) + ((1-Y) * np.log(1-A2))) * (-1/m)
        
        #calculating derivatives of Z2,W2,A1,W1 wrt cost function
        dZ2=(y-A2)*(-1/m)
        dW2=dZ2*A1
        dA1=dZ2*W2
        dW1=dA1*sigmoidDerivative(Z1)*x
        
        #updating weights 
        W2=W2-learning_rate*dW2
        W1=W1-learning_rate*dW1
        
    
    return W2,W1
W2,W1=backpropagation(W2,W1,A2,A1,Y)

NameError: name 'w2' is not defined

# Test Function

In [63]:
def test(x,y,W1,W2):
    Z1 = np.dot(w1, X_train) 
    A1 = sigmoid(Z1) 
    Z2 = np.dot(w2, A1)
    A2 = sigmoid(Z2)
    y_prediction=(A2>0.6)
    
    